root: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - jest
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
env:
  node: true
ignorePatterns:
  - dist
  - node_modules
  - examples
  - testdata
rules:
  "@typescript-eslint/explicit-module-boundary-types": off
  "@typescript-eslint/no-empty-function": warn
  "@typescript-eslint/no-inferrable-types": off
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/no-this-alias": off
  "@typescript-eslint/no-unused-vars": [warn, {argsIgnorePattern: ^_}]
  jest/expect-expect: off
  jest/no-disabled-tests: off
  jest/no-focused-tests: warn
  no-console: [warn, {allow: [warn, error, log]}]
  no-constant-condition: [off]
  no-debugger: error
  prefer-const: warn
overrides:
  - files:
      - "**/tests/*.test.ts"
    rules:
      no-explicit-any: off
      prefer-const: [off]
