# https://yarnpkg.com/configuration/yarnrc

enableGlobalCache: true
enableTimers: false

logFilters: # https://yarnpkg.com/advanced/error-codes
  - code: YN0032 # NODE_GYP_INJECTED
    level: discard
  - code: YN0062 # INCOMPATIBLE_OS
    level: discard
  - code: YN0076 # INCOMPATIBLE_ARCHITECTURE
    level: discard

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  # - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
  #   spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"

yarnPath: .yarn/releases/yarn-3.1.0.cjs
