root: true
extends:
  - eslint:recommended
env:
  browser: true
  es6: true
rules:
  no-debugger: error
  prefer-const: warn
ignorePatterns:
  - rollup.config.js
overrides:
  - files:
    - screenshot.js
    globals:
      __p5_server_screenshot_settings: true
      p5: true
