root: true
extends:
  - eslint:recommended
env:
  browser: true
  es6: true
rules:
  no-debugger: error
  prefer-const: warn
ignorePatterns:
  - "esbuild.config.ts"
  - "console-relay.ts"
parserOptions:
  sourceType: module
overrides:
  - files:
    - screenshot.js
    globals:
      __p5_server_screenshot_settings: readonly
      p5: readonly
