ignorePatterns:
  - "**/src/server/static/*.min.js"
overrides:
  - files:
      - "**/src/server/static/**/*.js"
    globals:
      callee: true
      console: true
      document: true
      fetch: true
      window: true
      WebSocket: true
    rules:
      no-console: [off]
      prefer-const: [off]
  - files:
      - "**/src/server/static/**/screenshot.js"
    globals:
      __p5_server_screenshot_settings: true
      p5: true
