name: Publish API Docs

on:
  push:
    branches: [docs, release]
  workflow_dispatch:
    tags:
      description: 'Publish API docs to GitHub Pages'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: npm install

      - name: Build Docs
        run: >
          | (cd p5-analysis && npm run build:docs)

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: p5-analysis/build/docs
