name: Publish API Docs

on:
  push:
    branches: [test-workflow]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          npm install -g yarn
          yarn install

      - name: Build Docs
        run: yarn run build:docs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: p5-analysis/build/docs
