name: unit-tests

on:
  push:
    branches: [master, test-workflow]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: yarn

      - name: Install
        run: |
          npm install -g yarn
          yarn install

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test
